# Generated by Django 5.1.2 on 2024-11-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KiwiQ_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='edges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graph',
            name='nodes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
