# Generated by Django 5.1.2 on 2024-11-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KiwiQ_App', '0002_alter_graph_edges_alter_graph_nodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('node_id', 'graph')},
        ),
    ]
